spring.application.name=SprintBootCRUD2
spring.datasource.url=jdbc:mysql://localhost:3306/springcrud
spring.datasource.username=root
spring.datasource.password=*admin123*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true